name: Chat Gist Updates

on:
  push:
    branches:
      - main

jobs:
  update-gist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch and update messages on GitHub Gist
        run: |
          curl -X PATCH \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            -d '{"files": {"chat.json": {"content": "NEW_CONTENT_HERE"}}}' \
            https://api.github.com/gists/6686b37f704607d66c455ceefef7fec6
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
