name: Example GitHub Actions Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use the secret
        run: |
          echo "The secret value is ${{ secrets.MY_API_TOKEN }}"
        env:
          MY_API_TOKEN: ${{ secrets.MY_API_TOKEN }}
