name: Deploy to Main Branch

on:
  push:
    branches:
      - main  # Trigger the workflow when there's a push to the 'main' branch

permissions:
  contents: write  # Allow writing to the repository (necessary for pushing changes)
  id-token: write  # Required for token-based authentication

jobs:
  deploy:
    runs-on: ubuntu-latest  # Run the job on the latest Ubuntu environment

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Git configuration (required for committing changes)
    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    # Step 3: Deploy to the 'main' branch (this is where the files will be pushed)
    - name: Deploy to Main Branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}  # Use the GitHub token for authentication
        publish_dir: ./  # Adjust this to specify which directory to publish (e.g., './build' if using a build step)
